SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE TYPE TimeZoneNames AS TABLE (
	TimeZoneName SYSNAME NOT NULL,
	PRIMARY KEY (TimeZoneName)
);
